### ISSUE TITLE
Совместимость со спецсимволами

### ISSUE THREAD

**Issue by x-plora** [mk90/LiquidCrystalRus#2]
При использовании библиотеки искажаются коды спецсимволов типа знака градусов (\x99) или вертикальных полосок (\x80 - \x83). Как победить эту проблему?

**Comment by mk90** [comment]
А какой код значка градуса в знакогенераторе дисплея? И второй вопрос, конечно - в соответствии с какой таблицей кодировки знаку градуса соответствует 0x99?

**Comment by x-plora** [comment]
http://www.melt.com.ru/docs/MT-20S4A.pdf
Страница символов 0

Все русские буквы выводятся корректно, но коды спецсимволов искажаются

**Comment by mk90** [comment]
Моя библиотека транслирует юникодные русские буквы в коды символов дисплеев. Могу согласиться с тем, что делает она это грубовато - захватывает и другие символы, отношения к кириллице не имеющие. Но если слегка уточнить диапазон (пара десятков байт на это потратится неизбежно) и обрабатывать **только** кириллицу, то остальные юникодные символы отображаться правильно не начнут, к сожалению. 

Поэтому, есть два варианта: 1. Добавить поддержку всех юникодных символов, а не только русских букв, но тогда это будет уже не LiquidCrystalRus, а LiquidCrystalRus+ (LiquidCrystalUTF?) 2. Ничего не делать, в скетче указывать непосредственно код символа в численном виде (для градуса - 0x99). Поскольку это не юникод, трансляция выполняться не будет, и всё должно выводиться корректно. 

Проблема имеет место быть, и даже не знаю, как лучше. Библиотека-то универсальная, в некоторых дисплеях не только никаких страниц нет, но и символов-то гораздо меньше - http://mk90.ru/files/datasheets/WH1602B-YGK-CTK.pdf

**Comment by x-plora** [comment]
А нет возможности добавить функцию printRaw для вывода строк без трансляции кодов символов?

**Comment by mk90** [comment]
Такая функция уже есть: send(код_символа, HIGH). Она объявлена как private, надо её в .h перенести в public.

**Comment by x-plora** [comment]
Попробую так.. Спасибо
