### ISSUE TITLE
Incompatible with 1.8.xx IDE / Несовместимо со средой 1.8.xx

### ISSUE THREAD

**Issue by lokapal** [mk90/LiquidCrystalRus#3]
Call to init LCD in 1.8.xx doesn't mention RW pin:

// initialize the library by associating any needed LCD interface pin
// with the arduino pin number it is connected to
const int rs = 8, en = 9, d4 = 4, d5 = 5, d6 = 6, d7 = 7;
LiquidCrystal lcd(rs, en, d4, d5, d6, d7);
All is working in english.

Moreover, at some shields rw pin is connected to the ground.
If I'm trying to set RW pin to 255 and call to Rus, no russian text at all:

#2  include <LiquidCrystalRus.h>
// initialize the library with the numbers of the interface pins
const int rs = 8, en = 9, d4 = 4, d5 = 5, d6 = 6, d7 = 7, rw = 255;
LiquidCrystalRus lcd(rs, rw, en, d4, d5, d6, d7);

English text is displayed correctly.

**Comment by mk90** [comment]
LiquidCrystalRus does not use feature "uploading custom characters"; only 4 characters available for upload - it is not enough to implement the Cyrillic support. You LCD **must** contain cyrillic font, there are no ways to show cyrilic text if not.

So, first of all: Is your LCD contains cyrillic font?

**Comment by MrSmartus** [comment]
yes, my display contains cyrillic font, model *WINSTAR **WH2004A-YYK-CT *
i use LiquidCrystalRus 1.6.1 and all displayed fine.

2017-08-21 12:34 GMT+03:00 Ilya Danilov <notifications@github.com>:

**Comment by mk90** [comment]
ArduinoIDE v1.8.4 Linux 64-bit, checking all LiquidCrystalRus examples: working fine, cyrillic text displayed correctly. It doesn't depend on RW pin: using six arguments constructor same as seven with rw = 255. It works always.

@lokapal wrote about "LiquidCrystal" in first example and "LiquidCrystalRus" in second, but it is a different libraries, maybe it were accidentally confused? 

Can you show me compilation log?

**Comment by mk90** [comment]
So far, no answers. Closing issue.
