### ISSUE TITLE
Коды символов перепутаны?

### ISSUE THREAD

**Issue by khusamov** [mk90/LiquidCrystalRus#6]
У вас в статье http://wiki.amperka.ru/products:display-lcd-text-20x4
написано, что коду B1 соответствует буква Я. 

Но вместо нее у меня выводится буква "б".

И собственно с остальными такая же путаница. Никак не получается вывести то что хочется.

**Comment by mxkmn** [comment]
Приветствую! Тоже столкнулся с этой проблемой. В общем там сложно взаимодействовать с print(), поэтому mk90 изменил write(), который теперь не работает с кодами >=0x80.

Я [сделал костыль](https://github.com/mxkmn/LiquidCrystalRus) через writeRaw(), будет работать :). Качай, проверяй.

**Comment by mk90** [comment]
> У вас в статье http://wiki.amperka.ru/products:display-lcd-text-20x4
> написано, что коду B1 соответствует буква Я.
> 
> Но вместо нее у меня выводится буква "б".
> 
> И собственно с остальными такая же путаница. Никак не получается вывести то что хочется.

Статья не моя, однако там про код B1 и его соответствие букве "Я" упоминается в разделе использования стандартной библиотеки LiquidCrystal, которая входит в ArduinoIDE. 

Исправьте инклуд в начале скетча на 

`LiquidCrystal lcd(12, 11, 5, 4, 3, 2);`

Должно заработать )

**Comment by mk90** [comment]
75eee6c: теперь в `print` можно сочетать русские буквы UTF-8 c прямыми кодами символов типа `\xB1`.

**Comment by mxkmn** [comment]
> [75eee6c](https://github.com/mk90/LiquidCrystalRus/commit/75eee6cd9cdbc33cedb35af19ebe06ed5be7df62): теперь в `print` можно сочетать русские буквы UTF-8.

И всё равно с кодами от 0xD0 до 0xD2 работать библиотека не будет (нужно отдельную write делать, [писал об этом](https://github.com/mxkmn/LiquidCrystalRus/blob/master/README.md)) :(.
Инфу про 0xD0-0xD2 бы куда-нибудь в readme...

И еще, если будут дальнейшие правки - было бы неплохо сделать фикс подсветки в keywords.txt
![image](https://user-images.githubusercontent.com/75564533/109474703-bdf8d980-7aaf-11eb-98f0-6d319509f358.png)

**Comment by mk90** [comment]
> И всё равно с кодами от 0xD0 до 0xD2 работать библиотека не будет (нужно отдельную write делать, [писал об этом](https://github.com/mxkmn/LiquidCrystalRus/blob/master/README.md)) :(.
> Инфу про 0xD0-0xD2 бы куда-нибудь в readme...

Библиотека действительно пытается транслировать символ, если он начинается с `0xd0` или `0xd1`. Но затевать ради этого отдельный метод считаю не вполне целесообразным. Ведь анализируется код и второго символа тоже - попадает ли он в диапазон русских букв. А если посмотреть, какие символы в знакогенераторе дисплея соответствуют диапазону `0x80..0xbf` - станет понятно, что это собственно и есть русские буквы, плюс пробельные символы.

Таким образом, если придерживаться простого правила - всегда печатать пробелы и русские буквы обычным способом, в юникоде (иначе странно, зачем вообще было париться с установкой этой библиотеки, не так ли?), можно свободно перемешивать их во `write` с любыми другими символами. 

Посмотрите пример `DumpCharacters`, в нем как раз выводятся все символы, том числе `0xd0` и `0xd1`.

> И еще, если будут дальнейшие правки - было бы неплохо сделать фикс подсветки в keywords.txt

Это запросто ) 531b1913e6c28b0ba70c2fbbb9837ae9e7119151
